### ISSUE TITLE
`snb-run -h` in fresh conda install gives ImportError

### ISSUE THREAD

**Issue by lucydot** [SMTG-Bham/ShakeNBreak#69]
Hello,

Using ShakeNBreak for the first time - it's great!

I've just installed on my HPC using conda (`conda install --channel conda-forge shakenbreak`) in a fresh conda environment.

Running `snb-run -h` gives the error `cannot import name _format_defect_name` from `doped.utils.plotting'`. 

I fixed it easy enough by removing the leading underscore from `_format_defect_name` where it occurs in `cli.py`, `plotting.py` and `energy_lowering_distortions.py`, and can see that your main branch also has these changes.

So I think a new conda release might fix this for other people? Just flagging up. Thanks!

**Comment by kavanase** [comment]
Hi @lucydot, thanks very much for flagging this!
Yes I realise our latest `conda` release is `3.3.0`, but `pip` / GitHub is `3.3.1`.
Sorry for the hassle with this, and thanks very much for the comprehensive info! 😃  Will fix asap

**Comment by kavanase** [comment]
Just fyi, now updated to have `3.3.1` as the latest `conda` release, thanks again Lucy!
https://anaconda.org/conda-forge/shakenbreak/files
