### ISSUE TITLE
Incompatibility with newly release pymatgen==5.31.2024

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [SMTG-Bham/ShakeNBreak#73]
FYI that there is an incompatability with pymatgen==5.31.2024:

```python
from doped.vasp import DefectDictSet
```

```python
    from pymatgen.io.vasp.sets import DictSet, UserPotcarFunctional
E   ImportError: cannot import name 'UserPotcarFunctional' from 'pymatgen.io.vasp.sets' (/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pymatgen/io/vasp/sets.py)
```

 This also, indirectly, effects shakenbreak via `from shakenbreak.input import Distortions`.

**Comment by kavanase** [comment]
Thanks for flagging Andrew! Will update now. The new update has also broken the CI as there's a misplaced `typing_extensions` again (https://github.com/materialsproject/pymatgen/pull/3752)

**Comment by Andrew-S-Rosen** [comment]
Sorry that I also keep posting on shakenbreak when I mean to post on doped!

**Comment by kavanase** [comment]
Haha no worries, the end justifies the means!
